### ISSUE TITLE
Worker can inherit unwriteable temporary directory

### ISSUE THREAD

**Issue by dracos** [lamby/pkg-gunicorn#21]
I have gunicorn installed on a jessie system that also has libpam-tmpdir installed. TEMP/TMP/TMPDIR/TEMPDIR are all set to /tmp/user/0 for a gunicorn process and all its children workers, even if the /etc/gunicorn.d/ file has a different user/group set. This then means the workers are unable to write temporary files as they don't have access to root's tempdir. I can set the environment variables to override this, but I wondered if there was something gunicorn could/should be doing about checking this when a user/group is set. No worries if not :)

**Comment by lamby** [comment]
Sorry to be That Guy, but could you refile this bug in one of two places:

 * gunicorn upstream, if you believe this to be not Debian-specific
 * The Debian BTS, if you believe this to be Debian-specific (or otherwise related to the Debian packaging)

Thanks!

**Comment by dracos** [comment]
Sure, I've filed upstream at https://github.com/benoitc/gunicorn/issues/1215 as it can happen outside Debian (though it's only with the Debian package that I have gunicorn running as root to begin with, I guess).
